name: PHP Unit Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set .env file
        run: |
          touch .env
          echo WWWUSER=${{ vars.WWWUSER }} >> .env
          echo WWWGROUP=${{ vars.WWWGROUP }} >> .env

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Start Docker Compose
        run: docker exec laravel composer install

      - name: Run PHPUnit tests
        run: docker exec laravel vendor/bin/phpunit --bootstrap vendor/autoload.php tests
