name: PHP Unit Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set .env file
        run: cp .env.example .env

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Start Docker Compose
        run: docker exec laravel composer install

      - name: Generate application encryption key
        run: docker exec laravel php artisan key:generate

      - name: Run PHPUnit tests
        run: docker exec laravel vendor/bin/phpunit --bootstrap vendor/autoload.php tests
